---

- name: Assemble and Generate configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname={{ inventory_hostname }}
        username=ansible
        password=ansible123
        dev_os={{ os }}
        filter='facts,interfaces,bgp_neighbors'
      register: result

    - debug: var=result
